config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students do
    resources :addresses
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :student_id, :description, :street, :city, :state, :zip, presence: true
  belongs_to :student, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, presence: true
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  has_many :addresses
  has_many :courses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
    redirect_to student_path(@student)
  end

  def create
    @student = Student.find(params[:student_id])
    address_data = address_params
    address_data[:student_id] = @student.id
    if Address.create!(address_data)
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  private

  def address_params
    params.require(:address).permit(:description, :street, :city, :state, :zip)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = Student.find(params[:id])
    @address = Address.new
    @address.student_id = @student.id
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    if @student.save
      flash[:success] = "#{@student.name} enrolled!"
      redirect_to student_path(@student)
    else
      flash[:fail] = 'Enrollment unsuccessful'
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    if @student.save
      flash[:success] = "#{@student.name} updated!"
      redirect_to student_path(@student)
    else
      flash[:fail] = 'Update failed'
      render :edit
    end
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy

    flash[:success] = "#{student.name} was successfully expelled!"
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<h3>Address</h3>

<%= form_for [ @student, @address ] do |f| %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :street %>
    <%= f.text_area :street %>
    <%= f.label :city %>
    <%= f.text_area :city %>
    <%= f.label :state %>
    <%= f.text_area :state %>
    <%= f.label :zip %>
    <%= f.text_area :zip %>
    <%= f.submit 'Save' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enrollment</title>
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <!-- navbar items, navbar burger... -->
    <%= link_to "Students", students_path, method: "get", class: "navbar-item"%>
    <%= link_to "Enroll a New Student", new_student_path, method: "get", class: "navbar-item"%>
  </div>
</nav>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/students/_address.html.erb
<div>
  <p>
    <%= address.description %></br>
    <%= address.street %></br>
    <%= address.city %>, <%= address.state %> <%= address.zip %></p>
</div>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit 'Save' %>
<% end %>

app/views/students/edit.html.erb
<h2>Edit <%= @student.name%></h2>

<%= render partial: "form" %>

app/views/students/index.html.erb
<h1>All Students</h1>
<% @students.each do |student| %>
  <div id="student-<%= student.id %>" >
    <%= link_to student.name, student_path(student) %>
    <%= button_to "Edit", edit_student_path(student) %>
    <%= button_to "Delete", student_path(student), method: "delete" %>
  </div>
<% end %>

app/views/students/new.html.erb
<h2>Enroll a new student</h2>

<%= render partial: "form" %>

app/views/students/show.html.erb
<%= button_to "Edit", edit_student_path(@student), method: 'get' %>
<%= button_to "Delete", student_path(@student), method: "delete" %>

<h1>Student Name</h1>
<%= @student.name %>

<%= render partial: 'addresses/form' %>
<%= render partial: 'students/address', collection: @student.addresses %>